In [1]:
import numpy as np

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


1. allows several Mathematical operations
2. Faster Operation

List vs Numpy - Time Taken

In [3]:
from time import process_time

In [8]:
np_array=np.array([i for i in range(1000000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(f"Time taken by numpy array: {end_time - start_time} seconds")


Time taken by numpy array: 0.015625 seconds


Numpy Arrays

In [9]:
#list
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [10]:
np_array=np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
# creating the one dimensional array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a.shape

(4,)

In [17]:
# two dimensional array
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
b.shape

(2, 4)

In [19]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholder in numpy arrays

In [22]:
# create a numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
#create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# array of a particular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [27]:
#create a identity matrix
a=np.eye(4) #no. of rows and columns are equal so only one argument
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
# create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.79793081 0.80616922 0.37148644 0.21968526]
 [0.62097561 0.4908034  0.37245456 0.90774257]
 [0.58077571 0.42175621 0.11905662 0.95304826]]


In [41]:
# Random integers  values array within a specific range
c=np.random.randint(1,100,(10,10))
print(c)
print(c[0][1])

[[40  7 86 64 13 10 65 11 96 46]
 [96 98 84 94 59 11 51 97  5 92]
 [60 69 79 98 30 53 15 55 56 50]
 [89 76 89 88 20 64 80 35 37 51]
 [54 35 37 10 11  7 21 22 39 33]
 [ 1 83 89 31 81 56 52 90 13 87]
 [36 70 54 54 57  5 16 16 13 72]
 [55 96  3 89 45 52 32 82 32 38]
 [14 43 61 52 59 78 21 66 40 39]
 [82 36 42 60 18 79 29  5 33 11]]
7


In [36]:
# array of evenly spaced value
d=np.linspace(10,30,5) #(range_start,range_end,no. of values)
print(d)

[10. 15. 20. 25. 30.]


In [38]:
# array of evenly spaced values--> specifying the step
e=np.arange(10,30,4) #steps method
print(e)

[10 14 18 22 26]


In [44]:
# convert a list to a numpy array
list2=[10,20,20,30,50]

np_array=np.asarray(list2)
print(type(np_array))
print(np_array)

<class 'numpy.ndarray'>
[10 20 20 30 50]


Analysing a numpy array

In [45]:
c=np.random.randint(10,90,(5,5))
print(c)

[[36 24 77 28 45]
 [74 17 46 65 88]
 [82 82 34 45 77]
 [59 68 66 85 10]
 [76 59 13 63 85]]


In [47]:
# array dimension
print(c.shape)


(5, 5)


In [48]:
#number of dimension
print(c.ndim)

2


In [49]:
# number of elements in an array
print(c.size)

25


In [50]:
# checking the datatype of the values in an array
print(c.dtype)

int32


Mathematical operation on a np array

In [52]:
list1 =[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)
#list datatype doesn't give mathematical operation it only join two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [53]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))


In [54]:
print(a)
print(b)

[[7 4 4]
 [5 7 4]
 [5 1 6]]
[[12 16 17]
 [16 12 13]
 [17 12 12]]


In [55]:
print(a+b)
# element wise addition

[[19 20 21]
 [21 19 17]
 [22 13 18]]


In [56]:
print(a-b)
print(a*b)
print(a/b)

[[ -5 -12 -13]
 [-11  -5  -9]
 [-12 -11  -6]]
[[84 64 68]
 [80 84 52]
 [85 12 72]]
[[0.58333333 0.25       0.23529412]
 [0.3125     0.58333333 0.30769231]
 [0.29411765 0.08333333 0.5       ]]


In [57]:
print(np.add(a,b))

[[19 20 21]
 [21 19 17]
 [22 13 18]]


Array Manipulation

In [58]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 8 8]
 [4 5 6]]
(2, 3)


In [61]:
#transpose\
trans=np.transpose(array)
print(trans)

[[9 4]
 [8 5]
 [8 6]]


In [62]:
#another way to find transpose
trans2=array.T
print(trans2)

[[9 4]
 [8 5]
 [8 6]]


In [63]:
# reshaping a array
a=np.random.randint(0,10,(2,3))

In [64]:
b=a.reshape(3,2)
print(b)
print(a)

[[7 1]
 [4 7]
 [2 0]]
[[7 1 4]
 [7 2 0]]
